### PR TITLE
Solve #58 by using `make` for the build

### PR DESCRIPTION
**Pull request by berewt**
Not checked yet

### CODE REVIEW

**Comment by teto** [comment]
I managed to fix the flake locally but I think a more elegant fix can be provided if https://github.com/idris-lang/Idris2/pull/1901 gets accepted.

**Comment by berewt** [comment]
It looks like a good idea. Usually, the feedback are quite fast on Idris project. We can wait for it and see how it goes... I think they could agree with it.

**Comment by teto** [comment]
I think this can be closed too ;)

**Comment by berewt** [comment]
Closed, adressed in #66.

**Pull request closed without merging**
